% h = animatedline;
% axis([0 4*pi -1 1])
% x = linspace(0,4*pi,2000);
% 
% for k = 1:length(x)
%     y = sin(x(k));
%     addpoints(h,x(k),y);
%     drawnow
% end
h = figure()
a1 = subplot(1,2,1);
gt_curve1 = animatedline(a1,'Linewidth',2,...
                        'MarkerSize',4,...
                        'MarkerFaceColor',[1 0 0],...
                         'MarkerEdgeColor','k');
set(a1,'xlim',[min(gt_pose_transformed(:,2))-.5, max(gt_pose_transformed(:,2))+.5],...
        'ylim',[min(gt_pose_transformed(:,3))-.5, max(gt_pose_transformed(:,3))+.5],...
        'zlim',[min(gt_pose_transformed(:,4))-.5, max(gt_pose_transformed(:,4))+.5]);
grid on 
xlabel(a1,'x(m)')
zlabel(a1,'z(m)')
view(a1,[0,1,0]);

a2 = subplot(1,2,2);
gt_curve2 = animatedline(a2,'Linewidth',2,...
                        'MarkerSize',4,...
                        'MarkerFaceColor',[1 0 0],...
                         'MarkerEdgeColor','k');
set(a2,'xlim',[min(gt_pose_transformed(:,2))-.5, max(gt_pose_transformed(:,2))+.5],...
        'ylim',[min(gt_pose_transformed(:,3))-.5, max(gt_pose_transformed(:,3))+.5],...
        'zlim',[min(gt_pose_transformed(:,4))-.5, max(gt_pose_transformed(:,4))+.5]);
grid on 
xlabel(a2,'x (m)')
ylabel(a2,'y(m)')
view(a2,[0,0,1])
% view(43,24);
time = t_opti;
pose = gt_pose_transformed;
plot_metadata.title_3d_position = 'Movement in 3D world - actual data Optitrack frame';
plot_metadata.title_angle = 'Optitrack - XYZ euler angle in degrees using rot ';
plot_metadata.title_position = 'Optitrack - position in optitrack frame - y up';
plot_metadata.view_vector = [0,1,0];
view(plot_metadata.view_vector);
opti_data_labels = {'x(m)','y(m)','z(m)'};
for i = 1:length(pose)
    addpoints(gt_curve1,gt_pose_transformed(i,2),gt_pose_transformed(i,3),gt_pose_transformed(i,4));
    drawnow
%     addpoints(gt_curve2,gt_pose_transformed(i,2),gt_pose_transformed(i,3),gt_pose_transformed(i,4));
%     drawnow
end
grid major 
xlabel('x (m)')
ylabel('y(m)')
zlabel('z(m)')
axis equal

% function plot_gt_data(figHandle,time,pose,euler_angle,plot_metadata)
%     
%     subplot(3,2,[1,2]);
%     plot3(pose(1,1),pose(1,2),pose(1,3),'*',...
%              'LineWidth',2,'MarkerSize',6,...
%              'MarkerEdgeColor','g','MarkerFaceColor',[0 1 0]);
%     hold on;
%     plot3(pose(:,1),pose(:,2),pose(:,3),'.',...
%              'LineWidth',2,'MarkerSize',4,...
%              'MarkerEdgeColor','k','MarkerFaceColor',[1 0 0]);
%          
%     hold on;
%     plot3(pose(end,1),pose(end,2),pose(end,3),'*',...
%              'LineWidth',2,'MarkerSize',6,...
%              'MarkerEdgeColor','r','MarkerFaceColor',[0 0 1]);
%     title(plot_metadata.title_3d_position,'interpreter','none');
%     
%     view(plot_metadata.view_vector);
%     annotation(figHandle,'textbox',...
%     [0.774706896551724 0.829393627954779 0.138008620689655 0.0308324768756424],...
%     'String',strcat('Number of poses =',num2str(length(time))),...
%     'FitBoxToText','off',...
%     'LineStyle','none');
%     xlabel('x (m)')
%     ylabel('y(m)')
%     zlabel('z(m)')
%     axis equal
% 
%     subplot(3,2,[3,4]);
%     s = stackedplot(time-time(1),euler_angle,...
%                 'Title',plot_metadata.title_angle,...
%                 'DisplayLabels',{'x(degrees)','y(degrees)','z(degrees)'},...
%                 'Marker','.',...
%                 'MarkerSize',2,...
%                 'LineStyle','none',...
%                 'GridVisible','on');
%      for i = 1:3
%          s.AxesProperties(i).YLimits = [0,360];
%      end

%     subplot(3,2,[5,6]);
%     s = stackedplot(time-time(1),pose(:,1:3),...
%                 'Title',plot_metadata.title_position,...
%                 'DisplayLabels',opti_data_labels,...
%                 'Marker','.',...
%                 'MarkerSize',2,...
%                 'LineStyle','none',...
%                 'GridVisible','on');
% end