close all
clear

script_paths;

raw_gt_data = xlsread('E:\Windows\Documents\Northeastern\NEUFRL\IMU_Paper_Part_2\MH_03_medium\mav0\state_groundtruth_estimate0\data.csv');

raw_imu_data = xlsread('E:\Windows\Documents\Northeastern\NEUFRL\IMU_Paper_Part_2\MH_03_medium\mav0\imu0\data.csv');

imu_start_ind = find(raw_imu_data(:,1) == raw_gt_data(1,1));
imu_end_ind = find(raw_imu_data(:,1) == raw_gt_data(end,1));

imu_data = parse_imu_data(raw_imu_data, imu_start_ind, imu_end_ind);

ground_truth_data = parse_gt_data(raw_gt_data);

save('euro_c_raw_data.mat', 'imu_data');
save('euro_c_ground_truth.mat', 'ground_truth_data');

function imu_data = parse_imu_data(raw_data, start_ind, end_ind)
dt = (raw_data(end_ind,1) - raw_data(start_ind,1))/length(raw_data(start_ind:end_ind,1)) *(10^-9); % seconds

imu_data = struct("time", (raw_data(start_ind:end_ind,1)- raw_data(start_ind,1)) * (10^-9), ...
                  "fs", 1 / dt, ...
                  "angular_velocity_x", raw_data(start_ind:end_ind,2), ...
                  "angular_velocity_y", raw_data(start_ind:end_ind,3), ...
                  "angular_velocity_z", raw_data(start_ind:end_ind,4), ...
                  "acceleration_x", raw_data(start_ind:end_ind,5), ...
                  "acceleration_y", raw_data(start_ind:end_ind,6), ...
                  "acceleration_z", raw_data(start_ind:end_ind,7));             
end

function ground_truth_data = parse_gt_data(raw_gt_data)
dt = (raw_gt_data(end,1) - raw_gt_data(1,1))/length(raw_gt_data(:,1)) *(10^-9); % seconds

ground_truth_data = struct("time", (raw_gt_data(:,1)- raw_gt_data(1,1)) * (10^-9), ...
                  "fs", 1 / dt, ...
                  "p_x", raw_gt_data(:,2), ...
                  "p_y", raw_gt_data(:,3), ...
                  "p_z", raw_gt_data(:,4), ...
                  "q_w", raw_gt_data(:,5), ...
                  "q_x", raw_gt_data(:,6), ...
                  "q_y", raw_gt_data(:,7), ...
                  "q_z", raw_gt_data(:,8), ...
                  "v_x", raw_gt_data(:,9), ...
                  "v_y", raw_gt_data(:,10), ...
                  "v_z", raw_gt_data(:,11), ...
                  "b_w_x", raw_gt_data(:,12), ...
                  "b_w_y", raw_gt_data(:,13), ...
                  "b_w_z", raw_gt_data(:,14), ...
                  "b_a_x", raw_gt_data(:,12), ...
                  "b_a_y", raw_gt_data(:,13), ...
                  "b_a_z", raw_gt_data(:,14));
              
end
