function plot_gt_data(figHandle,time,pose,euler_angle,plot_metadata)
    opti_data_labels = {'x(m)','y(m)','z(m)'};
    subplot(3,2,1);
    plot3(pose(1,1),pose(1,2),pose(1,3),'*',...
             'LineWidth',2,'MarkerSize',6,...
             'MarkerEdgeColor','g','MarkerFaceColor',[0 1 0]);
    hold on;
    plot3(pose(:,1),pose(:,2),pose(:,3),'.',...
             'LineWidth',2,'MarkerSize',4,...
             'MarkerEdgeColor','k','MarkerFaceColor',[1 0 0]);
         
    hold on;
    plot3(pose(end,1),pose(end,2),pose(end,3),'*',...
             'LineWidth',2,'MarkerSize',6,...
             'MarkerEdgeColor','r','MarkerFaceColor',[0 0 1]);
    xlabel('x(m)','FontSize',16)
    ylabel('y(m)','FontSize',16)
    zlabel('z(m)','FontSize',16)
    sgtitle(plot_metadata.title_3d_position,...
            'interpreter','none','FontSize',16);
    view(0,90)  % XY
    
    subplot(3,2,2);
    plot3(pose(1,1),pose(1,2),pose(1,3),'*',...
             'LineWidth',2,'MarkerSize',6,...
             'MarkerEdgeColor','g','MarkerFaceColor',[0 1 0]);
    hold on;
    plot3(pose(:,1),pose(:,2),pose(:,3),'.',...
             'LineWidth',2,'MarkerSize',4,...
             'MarkerEdgeColor','k','MarkerFaceColor',[1 0 0]);
         
    hold on;
    plot3(pose(end,1),pose(end,2),pose(end,3),'*',...
             'LineWidth',2,'MarkerSize',6,...
             'MarkerEdgeColor','r','MarkerFaceColor',[0 0 1]);
    xlabel('x(m)','FontSize',16)
    ylabel('y(m)','FontSize',16)
    zlabel('z(m)','FontSize',16)
    
    view(90,0) % YZ
    
%     annotation(figHandle,'textbox',...
%     [0.774706896551724 0.829393627954779 0.138008620689655 0.0308324768756424],...
%     'String','Green - start , Red - end ','FitBoxToText','off','LineStyle','none','FontSize',16);
    xlabel('x(m)','FontSize',16)
    ylabel('y(m)','FontSize',16)
    zlabel('z(m)','FontSize',16)
    axis equal

    subplot(3,2,[3,4]);
    s = stackedplot(time-time(1),euler_angle,...
                'Title',plot_metadata.title_angle,...
                'DisplayLabels',{'x(deg)','y(deg)','z(deg)'},...
                'Marker','.',...
                'MarkerSize',2,...
                'LineStyle','none',...
                'GridVisible','on',...
                'FontSize',16);
%      for i = 1:3
%          s.AxesProperties(i).YLimits = [0,360];
%      end

    subplot(3,2,[5,6]);
    s = stackedplot(time-time(1),pose(:,1:3),...
                'Title',plot_metadata.title_position,...
                'DisplayLabels',opti_data_labels,...
                'Marker','.',...
                'MarkerSize',2,...
                'LineStyle','none',...
                'GridVisible','on',...
                 'FontSize',16);
end
