function [t,X] = slice_and_form_mat(optitrack,timestamps_index)
% Dataformat: [px,py,pz,qx,qy,qz,qw]
    t = optitrack.msg_time(timestamps_index);
    p = [optitrack.position_x(timestamps_index),...
        optitrack.position_y(timestamps_index),...
        optitrack.position_z(timestamps_index)];
    quat_exist = 0;
    if(isfield(optitrack,'orientation_quat_x') ||...
       isfield(optitrack,'orientation_quat_y') ||...
       isfield(optitrack,'orientation_quat_z')||...
       isfield(optitrack,'orientation_quat_w'))
   
        q = [optitrack.orientation_quat_x(timestamps_index),...
                optitrack.orientation_quat_y(timestamps_index),...
                optitrack.orientation_quat_z(timestamps_index),...
                optitrack.orientation_quat_w(timestamps_index)];
        quat_exist = 1;
    end
    if quat_exist == 1
        X = [p,q];
    else
        X = p;
    end
end
