function h = plot_error_dead_reckoning_motion(time,error_dead_reckoned_imu_data,sigma)
    % sigma is 3xN vector for x,y and z (obtained from MC simulation)
    % dead_reckoned_imu_data: 3xN vector, position data (x,y,and z)
    % time: 1XN vector for time in seconds
    % later we will extend to 6 DOF.
    
    h = figure;
    y_labels = ['x','y','z'];
    [M1,N1] = size(error_dead_reckoned_imu_data);
    [M2,N2] = size(sigma);
    if length(time) == N1 && length(time) == N2
        for ax = 1:1 %to change this for multi-dimensional data. 
            hold on
            fill([time,time(end),time(1)],...
                [sigma(ax,:),sigma(ax,1),sigma(ax,1)],...
                'b',...
                'FaceAlpha',0.3);
            fill([time,time(end),time(1)],...
                [2*sigma(ax,:),sigma(ax,end),sigma(ax,1)],...
                'g',...
                'FaceAlpha',0.3);
            fill([time,time(end),time(1)],...
                [3*sigma(ax,:),2*sigma(ax,end),sigma(ax,1)],...
                'r',...
                'FaceAlpha',0.3);
            plot(time,error_dead_reckoned_imu_data,'-.b',...
                'LineWidth',2)
            grid on
            grid minor
            xlabel('t(s)')
            ylabel(strcat(y_labels(ax),'(m)'))
            legend('+/- 1 sigma',...
                '+/- 2 sigma',...
                '+/- 3 sigma',...
                'experimental error',...
                'Location','northwest')
        end
    end