%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/jagatpreet/Data/datasets/imu_modeling_paper/allan_dev_data/zed_2i_stationary_data_400hz_03212023.csv
%
% Auto-generated by MATLAB on 23-Mar-2023 16:59:35
clear all
%% Set up the Import Options and import the data
folder = "/media/jagatpreet/Data/datasets/imu_modeling_paper/allan_dev_data/";
filename = fullfile(folder,"zed_mini_stationary_data_800hz_03212023.csv");

opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["sample", "timeus", "axms2", "ay", "az", "wxdegs", "wy", "wz", "a_mag"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
raw_data = readtable(filename, opts);

%% Convert to output type
raw_data = table2array(raw_data);

%% Clear temporary variables
clear opts

% Form struct

ZED_mini.raw_data = raw_data;
ZED_mini.fs = 800;
ZED_mini.comment = strcat(num2str((length(raw_data)/ZED_mini.fs)/3600), 'hr');

% samples to scrap
% first 3 minutes and last 10 minutes
num_samples_to_scrap_from_begining = 30 * 60 * ZED_mini.fs;
num_samples_to_scrap_from_end = 10*60*ZED_mini.fs;
raw_data = raw_data(num_samples_to_scrap_from_begining: ...
                    end - num_samples_to_scrap_from_end , :); 

ZED_mini.Data.time = (raw_data(:, 2) - raw_data(1, 2))*1e-6;
ZED_mini.Data.acceleration_x = raw_data(:,3);
ZED_mini.Data.acceleration_y = raw_data(:,4);
ZED_mini.Data.acceleration_z = raw_data(:,5);
ZED_mini.Data.angular_velocity_x = deg2rad(raw_data(:,6));
ZED_mini.Data.angular_velocity_y = deg2rad(raw_data(:,7));
ZED_mini.Data.angular_velocity_z = deg2rad(raw_data(:,8));

save(fullfile(folder,"zed_mini.mat"), "ZED_mini", '-v7.3');