% read file 

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/jagatpreet/Data/datasets/imu_modeling_paper/allan_dev_data/icm20602_stationary_2.csv
%
% Auto-generated by MATLAB on 23-Mar-2023 15:52:58

%% file
folder = "/media/jagatpreet/Data/datasets/imu_modeling_paper/allan_dev_data/";
filename = fullfile(folder,"icm20602_stationary.csv");

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Index", "AccelXLSB", "AccelYLSB", "AccelZLSB", "GyroXLSB", "GyroYLSB", "GyroZLSB", "Var8"];
opts.SelectedVariableNames = ["Index", "AccelXLSB", "AccelYLSB", "AccelZLSB", "GyroXLSB", "GyroYLSB", "GyroZLSB"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var8", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var8", "EmptyFieldRule", "auto");

% Import the data
raw_data = readtable(filename, opts);

%% Convert to output type
raw_data = table2array(raw_data);

%% Clear temporary variables
clear opts

% Form struct

ICM20602.raw_data = raw_data;
ICM20602.fs = 200;
ICM20602.comment = strcat(num2str((length(raw_data)/ICM20602.fs)/3600), 'hr', ...
                  " Low noise mode\n collected using DK20602");
ICM20602.full_scale_range = "acc: +/-2g, gyro: 250 dps";
ICM20602.ADC_bits = 16;
ICM20602.acc_least_count = 4*9.81/2^16; % FSR / no. of bits
ICM20602.gyro_least_count = deg2rad(2*250/2^16); % FSR of gyro in dps
ICM20602.acc_least_count_unit = "m/s^2";
ICM20602.gyro_least_count_unit = "rad/s";
ICM20602.processed = zeros(size(raw_data));
dt = (1/ICM20602.fs);

% scrap first 30 minutes at start and last 10 minutes from end

num_samples_to_scrap_from_begining = 30 * 60 * ICM20602.fs;
num_samples_to_scrap_from_end = 10*60*ICM20602.fs;
raw_data = raw_data(num_samples_to_scrap_from_begining: ...
                    end - num_samples_to_scrap_from_end , :);

ICM20602.processed = zeros(size(raw_data));

% convert to acceleration in m/s^2 and angular rate in rad/s
ICM20602.processed(:, 1) = (0:length(raw_data) - 1) *dt;

ICM20602.processed(:, 2:4 ) = ...
    raw_data(:, 2:4) * ICM20602.acc_least_count;

ICM20602.processed(:, 5:7 ) = ...
    raw_data(:, 5:7) * ICM20602.gyro_least_count;

% std struct for data processing
ICM20602.Data.time = ICM20602.processed(:, 1);
ICM20602.Data.acceleration_x = ICM20602.processed(:,2);
ICM20602.Data.acceleration_y = ICM20602.processed(:,3);
ICM20602.Data.acceleration_z = ICM20602.processed(:,4);
ICM20602.Data.angular_velocity_x = ICM20602.processed(:,5);
ICM20602.Data.angular_velocity_y = ICM20602.processed(:,6);
ICM20602.Data.angular_velocity_z = ICM20602.processed(:,7);
save(fullfile(folder,'icm20602.mat'), 'ICM20602')